title: Tech Notes
tagline: "IT, (Cyber) Security & Smart Home"
description: >-
  Personal tech blog powered by Jekyll Chirpy
url: "https://<your-username>.github.io"
baseurl: ""   # empty for user site
author:
  name: Your Name
  avatar: /assets/img/avatar.png
theme: jekyll-theme-chirpy
