title: My Tech Notes
tagline: "IT, Cybersecurity & Smart Home"
description: >-
  My personal tech blog powered by Jekyll Chirpy
url: "https://<your-username>.github.io"
baseurl: ""   # keep empty unless it's a project site
author:
  name: Your Name
  avatar: /assets/img/avatar.png
